Replace method to get all application railties
Rails 4 API has changed and now we need to do:

  application.railties._all

Instead of just:

  application.railties._all

Otherwise it throws:

  undefined method `all' for #<Rails::Engine::Railties:0xa25b9e4> (NoMethodError)